name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: x-bananer
          outputs: |
            dist/github-snake.svg?color_snake=%236A4B93&color_dots=%23F8D4E3,%23EAD7FF,%23D6E4FF,%23C8EAF0,%23D8F0C8
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23C4B5FD&color_dots=%23313A5A,%23F28FAD,%23EAD7FF,%239CCFD8,%23D8F0C8

      - name: Deploy snake to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
