name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: x-bananer
          outputs: |
            dist/github-snake.svg?color_snake=%235A4B81&color_dots=%23F8F4FF,%23F3E8FF,%23D9ECFF,%23C9D6FF,%236A4B93
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23F28FAD&color_dots=%231F2335,%232A2F45,%23404C6B,%239CCFD8,%23EAD7FF

      - name: Deploy snake to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
