name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: x-bananer
          outputs: |
            outputs: |
              dist/github-snake.svg?color_snake=%23786DDB&color_dots=%23F4A7C1,%23E7C6FF,%23B8D4FF,%239CCFD8,%23B8F2C8,%23F6D365
              dist/github-snake-dark.svg?palette=github-dark&color_snake=%23A78BFA&color_dots=%23F28FAD,%23EAD7FF,%23C9D6FF,%239CCFD8,%23B8F2C8,%23F6D365

      - name: Deploy snake to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
